(deftheme color-theme-mfl "my custom theme")
(custom-theme-set-faces
  'color-theme-mfl
  '(default ((t (:foreground "#f5f5f4" :background "#000000"))))
  '(cursor ((t (:background "#fce94f"))))
  '(fringe ((t (:background "#1a1a1a"))))
  '(mode-line ((t (:foreground "#e3e3e3" :background "#243325"))))
  '(region ((t (:background "#014610"))))
  '(font-lock-builtin-face ((t (:foreground "#42e5ff"))))
  '(font-lock-comment-face ((t (:foreground "#c3ff6b"))))
  '(font-lock-function-name-face ((t (:foreground "#edd400"))))
  '(font-lock-keyword-face ((t (:foreground "#429eff"))))
  '(font-lock-string-face ((t (:foreground "#ffcbb3"))))
  '(font-lock-type-face ((t (:foreground"#7fcc33"))))
  '(font-lock-constant-face ((t (:foreground "#f8c16d"))))
  '(font-lock-variable-name-face ((t (:foreground "#ffa624"))))
  '(minibuffer-prompt ((t (:foreground "#729fcf" :bold t))))
  '(font-lock-warning-face ((t (:foreground "red" :bold t))))
)
(provide-theme 'color-theme-mfl)
